[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[language-server.texlab.config.texlab.build]
executable = "tectonic"
args = ["-X", "compile", "%f", "--synctex", "--keep-logs", "--keep-intermediates"]
onSave = true
forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onEdit = true

[language-server.rust-analyzer.config.check]
command = "clippy"

