alpha = 1

[palette] 
bg = "#1e1e1f"
fg = "#dcdcdb"
r0 = "#1e1e1f"
r1 = "#5f8a9f"
r2 = "#ac9674"
r3 = "#b6a086"
r4 = "#c3b69b"
r5 = "#ccbdaa"
r6 = "#cfcfaf"
r7 = "#dcdcdb"
b0 = "#1e1e1f"
b1 = "#5f8a9f"
b2 = "#ac9674"  
b3 = "#b6a086"
b4 = "#c3b69b"
b5 = "#ccbdaa"
b6 = "#cfcfaf"
b7 = "#dcdcdb" 
