theme:
  error_border: "217, 85, 85" # error dialog border is Red
  error_text: "227, 154, 101" # error message text (e.g. "Spotify API reported error 404") is Maroon
  hint: "233, 210, 108" # hint text in errors Yellow
  playbar_background: "24, 24, 37" # background of progress bar "Mantle"
  playbar_progress: "148, 221, 161" # filled-in part of the progress bar Green
  playbar_progress_text: "166, 173, 200" # song length and time played/left indicator in the progress bar "Subtext 0"
  playbar_text: "166, 173, 200" # artist name in player pane is "Subtext 0"
  inactive: "108, 112, 134" # borders of inactive panes "Overlay 0"
  text: "205, 214, 244" # text in panes is "Text"
  active: "203, 166, 247" # current playing song in list Mauve
  banner: "126, 183, 230" # the "spotify-tui" banner on launch Teal
  hovered: "216, 149, 199" # hovered pane border Pink
  selected: "216, 187, 231" # a) selected pane border, b) hovered item in list, & c) track title in player Lavender
  header: "216, 187, 231" # header text in panes (e.g. 'Title', 'Artist', etc.) Lavender

behavior: 
  volume_increment: 5
