audio_cache_size = 1000
use_nerdfont = true
library_tabs = ["tracks", "albums", "artists", "playlists"]

[theme]
#background = "#181818"
primary = "#CBCBCB"
secondary = "#DCDCDC"
title = "#952BEF"
playing = "#3836C7"
playing_selected = "#BB43CE"
#playing_bg = "#181818"
highlight = "#9E38F6"
highlight_bg = "#000000"
error = "#FFE4E4"
#error_bg = "#A50000"
statusbar = "#891CE7"
statusbar_progress = "#B43489"
#statusbar_bg = "#7419C2"
#cmdline = "#CBFFDE"
#cmdline_bg = "#444444"

